In [1]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print('Original array is:')
print(a)

print('Transpose of the original array is:')
b = a.T
print(b)

print('Sorted in C-style order:')
c = b.copy(order = 'C')
print(c)
for x in np.nditer(c):
    print(x, end=' ')

print('\nSorted in F-style order:')
c = b.copy(order = 'F')
print(c)
for x in np.nditer(c):
    print(x, end=' ')

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 20 40 5 25 45 10 30 50 15 35 55 
Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

In [2]:
a = np.arange(8)
print('The original array:')
print(a)
b = a.reshape(4,2)
print('The modified array:')
print(b)

The original array:
[0 1 2 3 4 5 6 7]
The modified array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [3]:
np.reshape(b,(2,4))


array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [10]:
a = np.arange(8).reshape(2,4)
print('The original array:')

print(a)

The original array:
[[0 1 2 3]
 [4 5 6 7]]


In [13]:
print(a.flat[2])

2


In [14]:
a = np.arange(8).reshape(2,4)

In [16]:
a = np.arange(42).reshape(3,2,7)

print('The original array is:')
print(a)

# default is column-major

print('The flattened array is:')
print(a.flatten())


print('The flattened array in F-style ordering:')
print(a.flatten(order='F'))

The original array is:
[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]

 [[28 29 30 31 32 33 34]
  [35 36 37 38 39 40 41]]]
The flattened array is:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41]
The flattened array in F-style ordering:
[ 0 14 28  7 21 35  1 15 29  8 22 36  2 16 30  9 23 37  3 17 31 10 24 38
  4 18 32 11 25 39  5 19 33 12 26 40  6 20 34 13 27 41]


In [18]:
a = np.arange(12).reshape(3,4)

print('The original array is:')
print(a)

print('The transposed array is:')
print(np.transpose(a))

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The transposed array is:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [19]:
a = np.arange(12).reshape(3,4)

print('The original array is:')
print(a)

print('Array after applying the function:')
print(a.T)

The original array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array after applying the function:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [20]:
a = np.array([[1,2],[3,4]])

print('First array:')
print(a)

b = np.array([[5,6],[7,8]])

print('Second array:')
print(b)

# both the arrays are of same dimensions

print('Joining the two arrays along axis 0:')
print(np.concatenate((a, b)))

print('Joining the two arrays along axis 1:')
print(np.concatenate((a, b), axis=1))

First array:
[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]
Joining the two arrays along axis 0:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joining the two arrays along axis 1:
[[1 2 5 6]
 [3 4 7 8]]


In [21]:
a = np.array([[1,2],[3,4]])

print('First Array:')
print(a)

b = np.array([[5,6],[7,8]])

print('Second Array:')
print(b)

print('Stack the two arrays along axis 0:')
print(np.stack((a, b), 0))

print('Stack the two arrays along axis 1:')
print(np.stack((a, b), 1))

First Array:
[[1 2]
 [3 4]]
Second Array:
[[5 6]
 [7 8]]
Stack the two arrays along axis 0:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Stack the two arrays along axis 1:
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [29]:
a = np.array([[1,2],[3,4]])
print('First array:')
print(a)

b = np.array([[5,6],[7,8]])

print('Second array:')
print(b)

print('Horizontal stacking:')
c = np.hstack((a,b))
print(c)
d = np.stack((a,b),axis = 1)
print(d)
e = np.vstack((a,b))
print(e)

First array:
[[1 2]
 [3 4]]
Second array:
[[5 6]
 [7 8]]
Horizontal stacking:
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [35]:
a = np.arange(9)
print('First array:')
print(a)
print('Split the array in 3 equal-sized subarrays:')
b = np.split(a,3)
print(b)

print('Split the array at positions indicated in 1-D array:')
b = np.split(a,[4,7])
print(b)


First array:
[0 1 2 3 4 5 6 7 8]
Split the array in 3 equal-sized subarrays:
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
Split the array at positions indicated in 1-D array:
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [37]:
a = np.arange(16).reshape(4,4)

print('First array:')
print(a)

print('Horizontal splitting:')
b = np.vsplit(a,2)
print(b)


First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizontal splitting:
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


In [40]:
c = np.vsplit(a,[2,3])
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [44]:
a = np.array([[1,2,3],[4,5,6]])

print('First array:')
print(a)

print('The shape of first array:')
print(a.shape)

b = np.resize(a, (3,19))

print('Second array:')
print(b)

print('The shape of second array:')
print(b.shape)

a= np.array([[1,2,3,4],[2,3,4,5]])
print(a.shape)
print(a.size)
b=a.reshape(4,2)
print(b)
c=np.resize(a,12)
print(c)

# Observe that first row of a is repeated in b since size is bigger

print('Resize the second array:')
b = np.resize(a,(3,3))
print(b)

First array:
[[1 2 3]
 [4 5 6]]
The shape of first array:
(2, 3)
Second array:
[[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1]
 [2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2]
 [3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3]]
The shape of second array:
(3, 19)
(2, 4)
8
[[1 2]
 [3 4]
 [2 3]
 [4 5]]
[1 2 3 4 2 3 4 5 1 2 3 4]
Resize the second array:
[[1 2 3]
 [4 2 3]
 [4 5 1]]


In [56]:
a = np.array([[1,2,3],[4,5,6]])

print('First array:')
print(a)

b = np.array([[7, 8, 9]])
print('Second array:')
print(b)
print('Append elements to array:')
print(np.append(a, b))

print('Append elements along axis 0:')
print(np.append(a, [[7, 8, 9]], axis=0))

print('Append elements along axis 1:')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))

First array:
[[1 2 3]
 [4 5 6]]
Second array:
[[7 8 9]]
Append elements to array:
[1 2 3 4 5 6 7 8 9]
Append elements along axis 0:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Append elements along axis 1:
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [57]:
a = np.array([[1,2],[3,4],[5,6]])

print('First array:')
print(a)

print('Axis parameter not passed. The input array is flattened before insertion.')
print(np.insert(a, 3, [11, 12]))

print('Axis parameter passed. The values array is broadcast to match input array.')

print('Broadcast along axis 0:')
print(np.insert(a, 1, [11], axis=0))

print('Broadcast along axis 1:')
print(np.insert(a, 1, 11, axis=1))



First array:
[[1 2]
 [3 4]
 [5 6]]
Axis parameter not passed. The input array is flattened before insertion.
[ 1  2  3 11 12  4  5  6]
Axis parameter passed. The values array is broadcast to match input array.
Broadcast along axis 0:
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]
Broadcast along axis 1:
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [61]:
a = np.arange(12).reshape(3,4)

print('First array:')
print(a)

print('Array flattened before delete operation as axis not used:')
print(np.delete(a, 5))

print('Column 2 deleted:')
print(np.delete(a, 0, axis=1))


First array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Array flattened before delete operation as axis not used:
[ 0  1  2  3  4  6  7  8  9 10 11]
Column 2 deleted:
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]


In [63]:
a = np.array([5,2,6,2,7,5,6,8,2,9])

print('First array:')
print(a)
print('\n')

print('Unique values of first array:')
u = np.unique(a)
print(u)
print('\n')

First array:
[5 2 6 2 7 5 6 8 2 9]


Unique values of first array:
[2 5 6 7 8 9]




In [64]:
print('Unique array and Indices array:')
u,indices = np.unique(a, return_index = True)
print(indices)

Unique array and Indices array:
[1 0 2 4 7 9]


In [67]:
print(a[indices])

[2 5 6 7 8 9]


In [70]:
u,count = np.unique(a,return_counts = True)
print(u)
print(count)


[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [73]:
a = np.array([1, 2, 2, 3, 1, 4, 5, 5, 6])
print(a)

print('Indices of unique array:')
u, indices = np.unique(a, return_inverse=True)
print(u)
print('\n')

print('Inverse are:')
print(indices)
print('\n')

print('Reconstruct the original array using indices:')
print(u[indices])
print('\n')

[1 2 2 3 1 4 5 5 6]
Indices of unique array:
[1 2 3 4 5 6]


Inverse are:
[0 1 1 2 0 3 4 4 5]


Reconstruct the original array using indices:
[1 2 2 3 1 4 5 5 6]




In [77]:
a = np.array([5,2,6,2,7,5,6,8,2,9])
u = np.unique(a)
print(u)
print('\n')




[2 5 6 7 8 9]




In [87]:
print("Orginal array",a)
print('Unique Values:')
u,indices = np.unique(a, return_index = True)
print(u)
print('Unique Indices:')
print(indices)
u,inverse = np.unique(a,return_inverse = True)
print('\n')
print('Inverces are:')
print(inverse)
print('\n')

print('Reconstruct the original array using indices:')
print(u[inverse])
print('\n')

print('Return the count of repetitions of unique elements:')
u,indices = np.unique(a,return_counts = True)
print(u)
print(indices)

Orginal array [5 2 6 2 7 5 6 8 2 9]
Unique Values:
[2 5 6 7 8 9]
Unique Indices:
[1 0 2 4 7 9]


Inverces are:
[1 0 2 0 3 1 2 4 0 5]


Reconstruct the original array using indices:
[5 2 6 2 7 5 6 8 2 9]


Return the count of repetitions of unique elements:
[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [89]:
print(np.char.add('hello', ' xyz'))

hello xyz


In [91]:
print(np.char.add(['Hello','Hi'],["abc","geh"]))

['Helloabc' 'Higeh']


In [92]:
print(np.char.multiply('Hello ', 3))

Hello Hello Hello 


In [101]:
print(np.char.center('hello', 20, fillchar='$'))

$$$$$$$hello$$$$$$$$


In [103]:
print(np.char.capitalize('hello world'))

Hello world


In [106]:
print(np.char.title('hello how are you?'))


Hello How Are You?


In [107]:
print(np.char.lower('HELLO'))

hello


In [108]:
print(np.char.upper(['hello', 'world']))

['HELLO' 'WORLD']


In [109]:
print(np.char.split('India, is my ,country', sep=','))

['India', ' is my ', 'country']


In [118]:
print(np.char.strip(['arora', 'admin', 'java'], 'a'))

['ror' 'dmin' 'jav']


In [121]:
print(np.char.join([':', '-'], ['dmy', 'ymd']))

['d:m:y' 'y-m-d']


In [122]:
print(np.char.replace('He is a good boy', 'is', 'was'))

He was a good boy


In [123]:
a = np.array([0,30,45,60,90])
print('Array containing sine values:')
sin = np.sin(a*np.pi/180)
print(sin)
print('\n')

print('Compute sine inverse of angles. Returned values are in radians.')
inv = np.arcsin(sin)
print(inv)
print('\n')

print('Check result by converting to degrees:')
print(np.degrees(inv))
print('\n')

Array containing sine values:
[0.         0.5        0.70710678 0.8660254  1.        ]


Compute sine inverse of angles. Returned values are in radians.
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


Check result by converting to degrees:
[ 0. 30. 45. 60. 90.]




In [130]:
a = np.array([1.0,5.55, 123, 0.567, 25.532])
print('Original array:')
print(a)

print('After rounding:')
print(np.around(a))
print(np.around(a, decimals=-1))

Original array:
[  1.      5.55  123.      0.567  25.532]
After rounding:
[  1.   6. 123.   1.  26.]
[  0.  10. 120.   0.  30.]
