In [2]:
import numpy as np

In [3]:
array_1 = np.array([1,2,3,4,5,0],dtype="int",)

In [4]:
array_1

array([1, 2, 3, 4, 5, 0])

In [5]:
array_1.itemsize

4

In [14]:
array_1 = np.array([1.0021,2,3,4,5,0],dtype="f2",)

array_1.dtype

dtype('float16')

In [15]:
array_1

array([1.002, 2.   , 3.   , 4.   , 5.   , 0.   ], dtype=float16)

In [9]:
sad = np.dtype("f2")

In [10]:
sad

dtype('float16')

In [32]:
dt = np.dtype([("Age","i2")])

In [33]:
dt

dtype([('Age', '<i2')])

In [34]:
nparray = np.array([10,20,30],dtype=dt)

In [37]:
nparray["Age"]

array([10, 20, 30], dtype=int16)

In [39]:
dt2 = np.dtype([("Name","S20"),("Age","i2"),("Marks","f4")])

In [44]:
np2 = np.array(("abc",12,12.05),dtype=dt2)

In [45]:
np2

array((b'abc', 12, 12.05),
      dtype=[('Name', 'S20'), ('Age', '<i2'), ('Marks', '<f4')])

In [50]:
np2["Name"]

array(b'abc', dtype='|S20')

In [51]:
np3 = np.array([1,2,3,4])

In [67]:
np3 = np.array([[1,2],[3,4]],dtype= "i2")

In [72]:
np3.dtype

dtype('int16')

In [74]:
np1 = np.arange(5)

In [91]:
np1 = np.array(([[3,4],[5,6],[6,7]]),dtype = int,order='f')

In [92]:
np1

array([[3, 4],
       [5, 6],
       [6, 7]])

In [95]:
np1 = np.linspace(0,10,3,True,)

In [96]:
np1

array([ 0.,  5., 10.])

In [100]:
a = np.arange(10)
print(a)
s  = slice(2,7,2)
a[s]

[0 1 2 3 4 5 6 7 8 9]


array([2, 4, 6])

In [101]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

# slice items starting from index
print('Now we will slice the array from the index a[1:]')
print(a[1:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Now we will slice the array from the index a[1:]
[[3 4 5]
 [4 5 6]]


In [103]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print('Our array is:')
print(a)
# this returns array of items in the second column
print('The items in the second column are:')
print(a[2, 1])

Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
The items in the second column are:
5


In [113]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
np.reshape(a,(9,1))

array([[1],
       [2],
       [3],
       [3],
       [4],
       [5],
       [4],
       [5],
       [6]])

In [119]:
a.flat[5]

5

In [120]:
a.flatten()

array([1, 2, 3, 3, 4, 5, 4, 5, 6])

In [121]:
from numpy import matlib

In [124]:
matlib.empty((3,4))

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
import numpy as np
print (np.inner(np.array([0,2]),np.array([0,1])) )


2


In [4]:
np2 = np.array([1,2,3])

In [5]:
np3 = np2*3

In [6]:
np3

array([3, 6, 9])

In [9]:
np4 = np.multiply(np2,3)

In [10]:
np4

array([3, 6, 9])

In [ ]:
# n = int(input("Enter a number: "))

# print("Prime numbers up to", n, "are:")

# for num in range(2, n + 1):
#     for i in range(2, num):
#         if num % i == 0:
#             print(num)
#             break
#     else:
#         print(num, end=" ")


Prime numbers up to 6 are:
4
6
