In [47]:
import numpy as np

In [48]:
import time
import numpy as np
size = 10
py_list1 = list(range(size))

start_time = time.time()
py_list_result = [x*10 for x in py_list1]
end_time = time.time()
print(f"Python list addition time: {end_time - start_time} seconds")

Python list addition time: 8.065712213516235 seconds


In [49]:
np_array1 = np.arange(size)

start_time = time.time()
np_array_result = np_array1 * 10
end_time = time.time()
print(f"NumPy array addition time: {end_time - start_time} seconds")

NumPy array addition time: 0.05348324775695801 seconds


### Creating an ndarray

In [50]:
# ndarray Parameters:
# object: Input data (list, tuple, etc.).
# dtype: Desired data type (e.g., int, float).
# copy: If True, the object is copied. Default is True.
# order: Memory layout ('C' for row-major, 'F' for column-major).
# subok: If True, subclasses are passed through. Default is False.
# ndmin: Minimum number of dimensions for the resulting array.

In [51]:
np1 = np.array([1,2,3,4])

In [52]:
np1

array([1, 2, 3, 4])

In [53]:
np2 = np.array([2,4,5,6,7], dtype="i4")

In [54]:
np2

array([2, 4, 5, 6, 7])

#### Create structured data types with multiple fields:

In [65]:
student_dtype = np.dtype([("Age","i8"),("Name","S10")])
student_dtype
np3 = np.array([(18,"Fysal"),("32","Gokul")],dtype = student_dtype)

In [67]:
print(np3)

[(18, b'Fysal') (32, b'Gokul')]


In [55]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array(arr1, copy=True)
arr1[0] = 99
print("arr1:", arr1)
print("arr2:", arr2) 


arr1: [99  2  3  4  5]
arr2: [1 2 3 4 5]


In [56]:
arr = np.array([[1],[ 2], [3], [4]], order='F')
print(arr)

[[1]
 [2]
 [3]
 [4]]


In [57]:
class MyArray(np.ndarray):
    pass
obj = MyArray((2, 2))
arr = np.array(obj, subok=True)
print(type(arr))


<class '__main__.MyArray'>


In [58]:
arr = np.array([1, 2, 3], ndmin=4)
print(arr)  # Output: [[1 2 3]]

[[[[1 2 3]]]]


#### Numpy Attributes

In [69]:
#shpe()
np3.shape

(2,)

In [78]:
np4 = np.array([[1,2,3],[4,5,6]], dtype = "i2")
np4.shape

(2, 3)

In [79]:
np4.shape = 3,2

In [80]:
np4

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int16)

In [81]:
np4.shape

(3, 2)

In [82]:
np4.itemsize

2

In [84]:
np4.nbytes

12

In [83]:
np4.size

6

In [86]:
np4.dtype

dtype('int16')

#### Array Creation Routines

In [ ]:
# numpy.empty

In [87]:
np5 = np.array([[[1,2,3],[5,6,8]]])

In [88]:
np5.ndim

3

In [89]:
np5.shape

(1, 2, 3)

In [90]:
np5

array([[[1, 2, 3],
        [5, 6, 8]]])

In [92]:
np6 = np.zeros((5,6))

In [93]:
np6

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [108]:
np7 = np.ones((2,6,6))

In [109]:
np7

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [110]:
np8 = np.full((5,6,7),100)

In [111]:
print(np8)

[[[100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]]

 [[100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]]

 [[100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]]

 [[100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]]

 [[100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]
  [100 100 100 100 100 100 100]]]


In [130]:
list1 = [1,2,3,4,5,6,7,8,9]
iter1 = iter(list1)

In [131]:
np9 = np.fromiter(iter1, dtype="i8")

In [132]:
np9

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [133]:
np10 = np.arange(10)

In [134]:
np10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
np11 = np.linspace(0,10,4, endpoint=False, retstep=False)

In [147]:
np11

array([0. , 2.5, 5. , 7.5])

In [148]:
np.random.rand(4,2)

array([[0.67022215, 0.4341026 ],
       [0.78687128, 0.05993992],
       [0.47694391, 0.83359305],
       [0.64856489, 0.46997189]])

In [149]:
np.random.randint(-4,8, size=(3,3))

array([[ 5,  1, -4],
       [ 0,  1,  0],
       [-4,  6,  3]])

### Indexing & Slicing

In [151]:
a = np.arange(10)
s = slice(2, 7, 2)
print(a)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [152]:
b = a[2:7:2]
print(b)

[2 4 6]


In [153]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a[1:]) 

[[3 4 5]
 [4 5 6]]


In [157]:
a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
a

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [155]:
print(a[..., 1])

[2 4 5]


In [156]:
print(a[2,...])

[4 5 6]


In [160]:
print(a[1,...])

[3 4 5]


### Advanced Indexing

In [161]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
y = arr1[[0, 1, 2], [0, 1, 0]]
print(y)

[1 4 5]


In [168]:
arr1 = np.array([[1, 2], [3, 4], [5, 6],[7,8],[9,10]])
y = arr1[[0, 1, 2], [0, 1, 0]]
print(y)

2


In [170]:
x = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8],
              [9, 10, 11]])

print(x[x > 5])

[ 6  7  8  9 10 11]
