In [1]:
import numpy as np

In [10]:
np1 = np.array([1,2,3,4,5],dtype = "i4",)

In [13]:
np2 = np.array(np1,copy=False)
np2

array([1, 2, 3, 4, 5])

In [18]:
# Create a 2x3 array with C-order (row-major)
arr_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')
print("Array in C-order (row-major):")
print(arr_c)

# Flatten the array to see how data is laid out in memory
print("Flattened C-order:", arr_c.flatten(order='C'))
print("Flattened F-order:", arr_c.flatten(order='F'))

# Create a 2x3 array with F-order (column-major)
arr_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')
print("\nArray in F-order (column-major):")
print(arr_f)
# Flatten the array to see how data is laid out in memory
print("Flattened C-order:", arr_f.flatten(order='C'))
print("Flattened F-order:", arr_f.flatten(order='F'))

Array in C-order (row-major):
[[1 2 3]
 [4 5 6]]
Flattened C-order: [1 2 3 4 5 6]
Flattened F-order: [1 4 2 5 3 6]

Array in F-order (column-major):
[[1 2 3]
 [4 5 6]]
Flattened C-order: [1 2 3 4 5 6]
Flattened F-order: [1 4 2 5 3 6]


In [19]:
import numpy as np

# Example 1: Create a 1D array with ndmin=1 (default)
arr1 = np.array([1, 2, 3], ndmin=1)
print("Array with ndmin=1:", arr1)
print("Shape:", arr1.shape)

# Example 2: Create a 1D array with ndmin=2
arr2 = np.array([1, 2, 3], ndmin=2)
print("\nArray with ndmin=2:", arr2)
print("Shape:", arr2.shape)

# Example 3: Create a 1D array with ndmin=3
arr3 = np.array([1, 2, 3], ndmin=3)
print("\nArray with ndmin=3:", arr3)
print("Shape:", arr3.shape)

Array with ndmin=1: [1 2 3]
Shape: (3,)

Array with ndmin=2: [[1 2 3]]
Shape: (1, 3)

Array with ndmin=3: [[[1 2 3]]]
Shape: (1, 1, 3)


In [22]:
dt = np.dtype([("Name","S20"),("Age","i2")])

In [26]:
np2 = np.array([("Rahul",20),("Alice",25)],dtype=dt)

In [27]:
np2

array([(b'Rahul', 20), (b'Alice', 25)],
      dtype=[('Name', 'S20'), ('Age', '<i2')])

In [28]:
np2["Age"]

array([20, 25], dtype=int16)

In [29]:
np2["Name"]

array([b'Rahul', b'Alice'], dtype='|S20')

In [40]:
import numpy as np

# Create a 2D array for demonstration
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]], dtype="int16")
print(arr)

# 1. Shape of the array
print("Shape:", arr.shape)  # (2, 3) because it's 2 rows and 3 columns

# 2. Number of dimensions
print("Number of dimensions:", arr.ndim)  # 2 because it's a 2D array

# 3. Total number of elements
print("Total elements:", arr.size)  # 6 because there are 6 elements in total

# 4. Memory size of each element (itemsize)
print("Item size (bytes):", arr.itemsize)  # 4 bytes, since int32 uses 4 bytes

# 5. Total memory size of the array (nbytes)
print("Total bytes:", arr.nbytes)  # 24 bytes (6 elements * 4 bytes each)

# 6. Data type of elements
print("Data type:", arr.dtype)  # int32

# 7. Transpose of the array
print("\nOriginal Array:\n", arr)
print("Transposed Array:\n", arr.T)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape: (2, 2, 3)
Number of dimensions: 3
Total elements: 12
Item size (bytes): 2
Total bytes: 24
Data type: int16

Original Array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Transposed Array:
 [[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]


In [41]:
arr.shape

(2, 2, 3)

In [42]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int16)

In [43]:
arr.shape = (3,2,2)

In [44]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [1, 2]],

       [[3, 4],
        [5, 6]]], dtype=int16)

In [48]:
np1 = np.arange(0,12,2,dtype="f2")
np1

array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float16)

In [64]:
np2 = np.empty((4,3,3),dtype="i2")

In [65]:
np2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [62]:
np3 = np.empty([4,3,3], dtype="i2")

In [63]:
np3

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [68]:
np3 = np.zeros((4,3,3),dtype = "i4")

In [69]:
np3

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [74]:
arr_fromiter = np.fromiter(range(100),np.int32,50)
print("\nArray from iterable:", arr_fromiter)
arr_fromiter.size


Array from iterable: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


50

In [87]:
np4 = np.linspace(1,10,6,retstep=True,dtype=np.int32)

In [88]:
np4

(array([ 1,  2,  4,  6,  8, 10]), 1.8)

In [90]:
np2= np.array([1,2,3,4,5])
s = slice(0,1,2)

In [92]:
print(np2[1:5:2])

[2 4]


In [97]:
a = np.array([[[1,2,3],[3,4,5],[4,5,6]],[[0,9,3],[8,5,1],[5,1,0]]])

In [107]:
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

In [114]:
arr[1,[0,2]]

array([40, 60])

In [115]:
arr[[0,2],[1,2]]

array([20, 90])

In [121]:
arr[[2]]

array([[70, 80, 90]])

In [122]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [135]:
fil = (arr > 10) & (arr < 30)

In [137]:
print(arr[fil])

[20]


In [130]:
fil1 = arr>10

In [131]:
arr[fil1]

array([20, 30, 40, 50, 60])

In [141]:
# Example 1: Broadcasting a 1D array to a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

print(arr_2d)
print(arr_1d)
# Broadcasting adds arr_1d to each row of arr_2d
result_1 = arr_2d + arr_1d
print("Broadcasted addition (2D + 1D):\n", result_1)

[[1 2 3]
 [4 5 6]]
[10 20 30]
Broadcasted addition (2D + 1D):
 [[11 22 33]
 [14 25 36]]


In [146]:
arr_3d = np.array([[[1], [2], [3]], [[4], [5], [6]]])  # Shape (2, 3, 1)
print(arr_3d)
arr_2d_b = np.array([[10, 20, 30]])  # Shape (1, 3)
print(arr_2d_b)
result_3 = arr_3d + arr_2d_b  # Broadcast to shape (2, 3, 3)
print("\nBroadcasted addition (3D + 2D):\n", result_3)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[10 20 30]]

Broadcasted addition (3D + 2D):
 [[[11 21 31]
  [12 22 32]
  [13 23 33]]

 [[14 24 34]
  [15 25 35]
  [16 26 36]]]
