In [1]:
import numpy as np

In [10]:
np1 = np.array([1,2,3,4,5],dtype = "i4",)

In [13]:
np2 = np.array(np1,copy=False)
np2

array([1, 2, 3, 4, 5])

In [18]:
# Create a 2x3 array with C-order (row-major)
arr_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')
print("Array in C-order (row-major):")
print(arr_c)

# Flatten the array to see how data is laid out in memory
print("Flattened C-order:", arr_c.flatten(order='C'))
print("Flattened F-order:", arr_c.flatten(order='F'))

# Create a 2x3 array with F-order (column-major)
arr_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')
print("\nArray in F-order (column-major):")
print(arr_f)
# Flatten the array to see how data is laid out in memory
print("Flattened C-order:", arr_f.flatten(order='C'))
print("Flattened F-order:", arr_f.flatten(order='F'))

Array in C-order (row-major):
[[1 2 3]
 [4 5 6]]
Flattened C-order: [1 2 3 4 5 6]
Flattened F-order: [1 4 2 5 3 6]

Array in F-order (column-major):
[[1 2 3]
 [4 5 6]]
Flattened C-order: [1 2 3 4 5 6]
Flattened F-order: [1 4 2 5 3 6]


In [19]:
import numpy as np

# Example 1: Create a 1D array with ndmin=1 (default)
arr1 = np.array([1, 2, 3], ndmin=1)
print("Array with ndmin=1:", arr1)
print("Shape:", arr1.shape)

# Example 2: Create a 1D array with ndmin=2
arr2 = np.array([1, 2, 3], ndmin=2)
print("\nArray with ndmin=2:", arr2)
print("Shape:", arr2.shape)

# Example 3: Create a 1D array with ndmin=3
arr3 = np.array([1, 2, 3], ndmin=3)
print("\nArray with ndmin=3:", arr3)
print("Shape:", arr3.shape)

Array with ndmin=1: [1 2 3]
Shape: (3,)

Array with ndmin=2: [[1 2 3]]
Shape: (1, 3)

Array with ndmin=3: [[[1 2 3]]]
Shape: (1, 1, 3)


In [22]:
dt = np.dtype([("Name","S20"),("Age","i2")])

In [26]:
np2 = np.array([("Rahul",20),("Alice",25)],dtype=dt)

In [27]:
np2

array([(b'Rahul', 20), (b'Alice', 25)],
      dtype=[('Name', 'S20'), ('Age', '<i2')])

In [28]:
np2["Age"]

array([20, 25], dtype=int16)

In [29]:
np2["Name"]

array([b'Rahul', b'Alice'], dtype='|S20')

In [40]:
import numpy as np

# Create a 2D array for demonstration
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]], dtype="int16")
print(arr)

# 1. Shape of the array
print("Shape:", arr.shape)  # (2, 3) because it's 2 rows and 3 columns

# 2. Number of dimensions
print("Number of dimensions:", arr.ndim)  # 2 because it's a 2D array

# 3. Total number of elements
print("Total elements:", arr.size)  # 6 because there are 6 elements in total

# 4. Memory size of each element (itemsize)
print("Item size (bytes):", arr.itemsize)  # 4 bytes, since int32 uses 4 bytes

# 5. Total memory size of the array (nbytes)
print("Total bytes:", arr.nbytes)  # 24 bytes (6 elements * 4 bytes each)

# 6. Data type of elements
print("Data type:", arr.dtype)  # int32

# 7. Transpose of the array
print("\nOriginal Array:\n", arr)
print("Transposed Array:\n", arr.T)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape: (2, 2, 3)
Number of dimensions: 3
Total elements: 12
Item size (bytes): 2
Total bytes: 24
Data type: int16

Original Array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Transposed Array:
 [[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]


In [41]:
arr.shape

(2, 2, 3)

In [42]:
arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int16)

In [43]:
arr.shape = (3,2,2)

In [44]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [1, 2]],

       [[3, 4],
        [5, 6]]], dtype=int16)

In [48]:
np1 = np.arange(0,12,2,dtype="f2")
np1

array([ 0.,  2.,  4.,  6.,  8., 10.], dtype=float16)

In [64]:
np2 = np.empty((4,3,3),dtype="i2")

In [65]:
np2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [62]:
np3 = np.empty([4,3,3], dtype="i2")

In [63]:
np3

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int16)

In [68]:
np3 = np.zeros((4,3,3),dtype = "i4")

In [69]:
np3

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [74]:
arr_fromiter = np.fromiter(range(100),np.int32,50)
print("\nArray from iterable:", arr_fromiter)
arr_fromiter.size


Array from iterable: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


50

In [87]:
np4 = np.linspace(1,10,6,retstep=True,dtype=np.int32)

In [88]:
np4

(array([ 1,  2,  4,  6,  8, 10]), 1.8)

In [90]:
np2= np.array([1,2,3,4,5])
s = slice(0,1,2)

In [92]:
print(np2[1:5:2])

[2 4]


In [97]:
a = np.array([[[1,2,3],[3,4,5],[4,5,6]],[[0,9,3],[8,5,1],[5,1,0]]])

In [107]:
arr = np.array([[10, 20, 30], 
                [40, 50, 60], 
                [70, 80, 90]])

In [114]:
arr[1,[0,2]]

array([40, 60])

In [115]:
arr[[0,2],[1,2]]

array([20, 90])

In [121]:
arr[[2]]

array([[70, 80, 90]])

In [122]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [135]:
fil = (arr > 10) & (arr < 30)

In [137]:
print(arr[fil])

[20]


In [130]:
fil1 = arr>10

In [131]:
arr[fil1]

array([20, 30, 40, 50, 60])

In [141]:
# Example 1: Broadcasting a 1D array to a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

print(arr_2d)
print(arr_1d)
# Broadcasting adds arr_1d to each row of arr_2d
result_1 = arr_2d + arr_1d
print("Broadcasted addition (2D + 1D):\n", result_1)

[[1 2 3]
 [4 5 6]]
[10 20 30]
Broadcasted addition (2D + 1D):
 [[11 22 33]
 [14 25 36]]


In [146]:
arr_3d = np.array([[[1], [2], [3]], [[4], [5], [6]]])  # Shape (2, 3, 1)
print(arr_3d)
arr_2d_b = np.array([[10, 20, 30]])  # Shape (1, 3)
print(arr_2d_b)
result_3 = arr_3d + arr_2d_b  # Broadcast to shape (2, 3, 3)
print("\nBroadcasted addition (3D + 2D):\n", result_3)

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]
[[10 20 30]]

Broadcasted addition (3D + 2D):
 [[[11 21 31]
  [12 22 32]
  [13 23 33]]

 [[14 24 34]
  [15 25 35]
  [16 26 36]]]


In [1]:
import numpy as np

In [4]:
np2 = np.array([1,2,3,4])
print(np.reshape(np2,(1,2,2)))

[[[1 2]
  [3 4]]]


In [3]:
np2

array([1, 2, 3, 4])

In [6]:
np2.reshape(2,1,2)

array([[[1, 2]],

       [[3, 4]]])

In [12]:
a = np.arange(8)
print('The original array:')
print(a)
b = a.reshape((4,2))
print('The modified array:')
print(b)


The original array:
[0 1 2 3 4 5 6 7]
The modified array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [16]:
a = np.arange(8).reshape(2,4)
print('The original array:')
print(a)

print('After applying the flat function:')
# returns element corresponding to index in flattened array
print(a.flat[5])
print(a)

for i in a.flat:
    print(i)

The original array:
[[0 1 2 3]
 [4 5 6 7]]
After applying the flat function:
5
[[0 1 2 3]
 [4 5 6 7]]
0
1
2
3
4
5
6
7


In [17]:
arr = np.array([[1, 2], [3, 4]])

# Modify the second element in a flattened view
arr.flat[1] = 99

print("Array after modifying the second element:")
print(arr)

Array after modifying the second element:
[[ 1 99]
 [ 3  4]]


In [18]:
arr.flatten()

array([ 1, 99,  3,  4])

In [20]:
# Create a 3D array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

# Transpose the 3D array by changing axes order
transposed_3D = np.transpose(arr, (1, 0, 2))
print("Original array shape:", arr.shape)
print("Transposed array shape:", transposed_3D.shape)
print("Transposed 3D array:\n", transposed_3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Original array shape: (2, 2, 2)
Transposed array shape: (2, 2, 2)
Transposed 3D array:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [27]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1)
print(arr2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [26]:
np.concatenate((arr1,arr2),0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [28]:
np.concatenate((arr1,arr2),1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [31]:
np.stack((arr1,arr2),axis=0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [32]:
np.stack((arr1,arr2), axis= 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [33]:
np.hstack((arr1,arr2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [38]:
d2 = np.array([[1,2,3],[4,5,6]])

In [39]:
d2.shape

(2, 3)

In [2]:
import numpy as np

In [6]:
np2 = np.array([5,4,3,2,1,0])

np.hsplit(np2,2)

[array([5, 4, 3]), array([2, 1, 0])]

In [11]:
np.split(np2,2, axis=0)

[array([5, 4, 3]), array([2, 1, 0])]

In [15]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

# Vertical split (same as split along axis=0)
vsplit_result = np.vsplit(arr, 2)  # Splits into two sub-arrays by rows
print(vsplit_result)

# Horizontal split (same as split along axis=1)
hsplit_result = np.hsplit(arr, 2)  # Splits into two sub-arrays by columns
print(hsplit_result)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [18]:
np.split(arr,2,axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [23]:
arr = np.array([[1, 2], [3, 4]])
appended_axis0 = np.append(arr, [[5, 6]], axis=0)  # Adds as a new row
appended_axis1 = np.append(arr, [[5],[6]], axis=1)  # Adds as a new column

print("Original array:\n", arr)
print("Appended along axis 0:\n", appended_axis0)
print("Appended along axis 1:\n", appended_axis1)

Original array:
 [[1 2]
 [3 4]]
Appended along axis 0:
 [[1 2]
 [3 4]
 [5 6]]
Appended along axis 1:
 [[1 2 5]
 [3 4 6]]


In [24]:
a=np.array([0,30,45,60,90])

In [25]:
a = np.radians(a)

In [26]:
np.sin(a)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [27]:
# Create an integer array
a = np.array([1, 2, 3, 4, 0], dtype=int)

# Calculate the reciprocal
reciprocal_a = np.reciprocal(a)

# Display the results
print("Original Array:\n", a)
print("Reciprocal Array:\n", reciprocal_a)

Original Array:
 [1 2 3 4 0]
Reciprocal Array:
 [          1           0           0           0 -2147483648]


C:\Users\CHROMIUM\AppData\Local\Temp\ipykernel_2596\1848087755.py:5: RuntimeWarning: divide by zero encountered in reciprocal
  reciprocal_a = np.reciprocal(a)
C:\Users\CHROMIUM\AppData\Local\Temp\ipykernel_2596\1848087755.py:5: RuntimeWarning: invalid value encountered in reciprocal
  reciprocal_a = np.reciprocal(a)


In [1]:
import numpy as np

# Test values for a and b
a = np.array([-7, 7])
b = np.array([3, 3])

# Calculate modulus and remainder
mod_result = np.mod(a, b)
remainder_result = np.remainder(a, b)

# Display results
print("a:", a)
print("b:", b)
print("np.mod(a, b):", mod_result)
print("np.remainder(a, b):", remainder_result)



a: [-7  7]
b: [3 3]
np.mod(a, b): [2 1]
np.remainder(a, b): [2 1]


In [4]:
import numpy as np

# Positive and negative dividends and divisors
a = np.array([7, 7])
b = np.array([3, 3])

# Calculate modulus and remainder
mod_result = np.mod(a, b)
remainder_result = np.remainder(a, b)

# Display results
print("a:", a)
print("b:", b)
print("np.mod(a, b):", mod_result)
print("np.remainder(a, b):", remainder_result)


a: [7 7]
b: [3 3]
np.mod(a, b): [1 1]
np.remainder(a, b): [1 1]


In [3]:
import numpy as np
a = np.array([-5.6j, 0.2j, 11. , 1+1j])

print('Our array is:')
print(a)
print('\n')

print('Applying real() function:')
print(np.real(a))
print('\n')

print('Applying imag() function:')
print(np.imag(a))
print('\n')

print('Applying conj() function:')
print(np.conj(a))
print('\n')

print('Applying angle() function:')
print(np.angle(a))
print('\n')

print('Applying angle() function again (result in degrees)')
print(np.angle(a, deg=True))


Our array is:
[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]


Applying real() function:
[-0.  0. 11.  1.]


Applying imag() function:
[-5.6  0.2  0.   1. ]


Applying conj() function:
[-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


Applying angle() function:
[-1.57079633  1.57079633  0.          0.78539816]


Applying angle() function again (result in degrees)
[-90.  90.   0.  45.]


In [15]:
import numpy as np

data = np.array([[1, 2, 3], [4, 5, 6]])
# print(data)

# # Maximum and minimum values
# max_value = np.amax(data)
# min_value = np.amin(data)

# # Along a specific axis
# print(np.amax(data, axis=1))
print(np.amax(data, axis=0))

# print("Max value:", max_value)          # 6
# print("Min value:", min_value)          # 1



[4 5 6]


In [ ]:
weights = np.array([0.1, 0.2, 0.7])
print(np.mean([1, 2, 3]))



2.0


In [31]:
import numpy as np

arr = np.array([[3, 1, 2], [6, 4, 11],[10,8,9]])

# Sort along the last axis (columns)
sorted_array = np.sort(arr, axis=1)

print("Sorted array:\n", sorted_array)

Sorted array:
 [[ 1  2  3]
 [ 4  6 11]
 [ 8  9 10]]


In [32]:
print(arr)

[[ 3  1  2]
 [ 6  4 11]
 [10  8  9]]


In [33]:
print(np.sort(arr,axis=1))

[[ 1  2  3]
 [ 4  6 11]
 [ 8  9 10]]


In [34]:
print(np.sort(arr,axis=0))

[[ 3  1  2]
 [ 6  4  9]
 [10  8 11]]


In [35]:
import numpy as np

# Define a structured array with fields 'name', 'age', and 'height'
data = np.array([
    ('Alice', 25, 5.5),
    ('Bob', 23, 5.8),
    ('Charlie', 35, 5.7),
    ('Diana', 30, 5.9)
], dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])


In [44]:
# Sort by age
sorted_by_age = np.sort(data, order=['age','name'])
print("Sorted by age:\n", sorted_by_age)


Sorted by age:
 [('Bob', 23, 5.8) ('Alice', 25, 5.5) ('Diana', 30, 5.9)
 ('Charlie', 35, 5.7)]


In [45]:
arr = np.array([[1, 2, 3], [6, 5, 4]])

# Find index of max and min
max_index = np.argmax(arr)
min_index = np.argmin(arr)

print("Index of max:", max_index)  # 3 (flat index in 1D)
print("Index of min:", min_index)  # 0


Index of max: 3
Index of min: 0


In [48]:
arr = np.array([[5, 12, 15],
                [20, 1, 25],
                [10, 30, 5]])

# Find the index of the max element along each column (axis=0)
max_indices_axis0 = np.argmax(arr, axis=0)
print("Array:\n", arr)
print("Max indices along axis 0:", max_indices_axis0)  # Output: [1, 2, 1]

# Find the index of the max element along each row (axis=1)
max_indices_axis1 = np.argmax(arr, axis=1)
print("Max indices along axis 1:", max_indices_axis1)  # Output: [2, 2, 1]


Array:
 [[ 5 12 15]
 [20  1 25]
 [10 30  5]]
Max indices along axis 0: [1 2 1]
Max indices along axis 1: [2 2 1]


In [49]:
print(np.argmax(arr))

7


In [50]:
import numpy as np

arr = np.array([0, 2, 0, 3, 4, 0])
non_zero_indices = np.nonzero(arr)

print("Array:", arr)
print("Indices of non-zero elements:", non_zero_indices)  # Output will be (array([1, 3, 4]),)


Array: [0 2 0 3 4 0]
Indices of non-zero elements: (array([1, 3, 4], dtype=int64),)


In [51]:
arr = np.array([[0, 1, 0],
                [2, 0, 3],
                [4, 0, 0]])

non_zero_indices = np.nonzero(arr)
print("Array:\n", arr)
print("Indices of non-zero elements:", non_zero_indices)


Array:
 [[0 1 0]
 [2 0 3]
 [4 0 0]]
Indices of non-zero elements: (array([0, 1, 1, 2], dtype=int64), array([1, 0, 2, 0], dtype=int64))


In [53]:
arr[[0,1,1,2],[1,0,2,0]]

array([1, 2, 3, 4])

In [55]:
import numpy as np
x = np.arange(9).reshape(3, 3)

print('Our array is:')
print(x)

Our array is:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [59]:
arr = np.array([[0,1,1,6],[1,7,2,0]])

In [61]:
cond = np.where(arr>5)
print(cond)

(array([0, 1], dtype=int64), array([3, 1], dtype=int64))


In [62]:
print(arr[cond])

[6 7]


In [63]:
cond = np.where(arr>5,"YES","NO")

In [65]:
print(cond)

[['NO' 'NO' 'NO' 'YES']
 ['NO' 'YES' 'NO' 'NO']]


In [67]:
even = np.where(arr %2 == 0)

In [68]:
print(arr[even])

[0 6 2 0]
