In [20]:
import numpy as np

In [39]:
array1 = np.array([1,2,3,4],dtype="i8")

In [40]:
print(array1)

[1 2 3 4]


In [1]:
x = []
for i in range(1,11):
    x.append(i)

In [2]:
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [6]:
y = [x for x in range(1,11)]

In [7]:
print(y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [8]:
square = [ sq **2 for sq in range(1,11)]
print(square)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [30]:
import time
size = 100000000

In [ ]:
# numbers = list(range(size))
# result = []
# st = time.time()
# for i in numbers:
#     result.append(i*10)
# end = time.time()
# print(end-st)


30.507822036743164


In [ ]:
# arr_1 = np.arange(size)
# st = time.time()
# result = np.multiply(arr_1,10)
# end = time.time()
# print(end-st)

2.990050792694092


In [ ]:
0 - O dimension
[1,2] -  1 dimension
[[1,2]] - 2 diemnsion
[[[1,2]]] - 3 dimension
.
.
.
.
.
.         - n dimension


In [37]:
array_1 = np.array([1,2,3,4])

In [39]:
array_1*10

array([10, 20, 30, 40])

In [43]:
list_1 = [1,2,3,4]
print(type(list_1))

<class 'list'>


In [44]:
array_2 = np.array(list_1)

In [46]:
print(array_2)

[1 2 3 4]


In [49]:
zerodim = np.array(0)

In [50]:
print(zerodim.ndim)

0


In [77]:
array_1 = np.array([1,2,3,0],np.bool_,ndmin = 2)

In [78]:
array_1


array([[ True,  True,  True, False]])

In [71]:
array_1.ndim

2

In [82]:
dt = np.dtype("int64")
print(dt)

int64


In [83]:
array_1 = np.array([1,2,3,0],dt,ndmin = 2)

In [84]:
array_1.dtype

dtype('int64')

In [8]:
import numpy as np
a = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])
print(a)
a.shape = (12,1,1)
print(a)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]

 [[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]]


In [15]:
print(a.size)

12


In [13]:
x = np.array([1,2,3,4,5], dtype = "int32")
print(x)
print(x.itemsize)


[1 2 3 4 5]
4


In [17]:
x.nbytes

20

In [18]:
x = 2
y = 5
print(x ** y)

32


In [20]:
x = np.empty([3,2])
print(x)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 4.24399158e-314]
 [8.48798317e-314 1.27319747e-313]]


In [31]:
list2 = [1,3,4,5]

# use iterator to create ndarray
x = np.fromiter(list2, dtype = float)
print(x)

[1. 3. 4. 5.]


In [34]:
x = np.linspace(10,20, 5, endpoint = True, retstep=True)
print(x)

(array([10. , 12.5, 15. , 17.5, 20. ]), 2.5)
